### ISSUE TITLE
file project.json

### ISSUE THREAD

**Issue by EParedez** [janaks09/NetCoreSaaS#1]
where the file project.json is localled, i need to install a depedency, but i can't find it

**Comment by janaks09** [comment]
@EParedez This project is based on `MSBuild/csproj ` format in which `project.json` is not supported anymore. If you want still want to develop using `project.json` format then checkout this series http://benfoster.io/blog/tagged/multi-tenancy else you need to upgrade your project and continue with this sample. More here https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj

**Comment by EParedez** [comment]
Thank you very much for clarifying this topic

**Comment by janaks09** [comment]
No problem.
