### ISSUE TITLE
.NET Core Web API

### ISSUE THREAD

**Issue by CMTietgen** [janaks09/NetCoreSaaS#2]
Firstly, thanks for creating this sample project.

Secondly, this isn't really an issue, but it would be cool to see a .NET Core Web API sample project too.

My goal is to have a .NET Core Web API back end and either an Angular, React, or Vue front end.

**Comment by janaks09** [comment]
@CMTietgen  I am planning to add Web API project too. Will update on this discussion once i get it done.
