### ISSUE TITLE
Project can not start

### ISSUE THREAD

**Issue by canperk** [janaks09/NetCoreSaaS#3]
I have run the project and project gives that error below
`InvalidOperationException: No service for type 'NetCoreSaaS.Data.Entities.Catalog.Tenant' has been registered.`

Then I have added AddScoped Tenant to Tenant but it was a strange trial to solve it. It has stopped giving the exception but main problem is project cannot resolce localhost:60001 and tenant1 & tenant2 subdomains neither. 

What did i missed to get a succeded result?

**Comment by janaks09** [comment]
@canperk  Did you solve this issue or still getting one?

**Comment by janaks09** [comment]
LMK if you need any help with this issue.

**Comment by canperk** [comment]
I solved my problem by doing a new solution which is provided your tenant classes. And I have created a web site on iis and set it an address with DNS names. It is working as tenant server but I dont know if it was the right way...

**Comment by TomBeckett** [comment]
Hey @janaks09 

I'm also receiving this error. So far I've cloned the project, built it (restoring dependencies/migrations), switched to Kestral (to make sure I have the right port etc) and ran it.

If I navigate to tenant1 or tenant2.localhost:6001 I get a generic 404/no server running browser error.

If I navigate to localhost:6001 the precise error I receive is : 

> InvalidOperationException: No service for type 'NetCoreSaaS.Data.Entities.Catalog.Tenant' has been registered.

See atttached for stacktrace.
[stack.txt](https://github.com/janaks09/NetCoreSaaS/files/1565937/stack.txt)

Any ideas? Would really love to use this library it sincerely sounds perfect for my use case 💯 

Thanks,
Tom

**Comment by ramusbucket** [comment]
This error essentially means, tenant has not been resolved. 

if you see his Tenant resolvers under - `NetCoreSaaS.WebHost/Infrastructures/TenantResolver`, he is trying to get Tenant name from host url. And his database initializes it to `tenant1.localhost:6001` and so on. If your development server is running on a different port, it is not going to match. 

Another solution could be to change the way tenant is resolved and default tenant value. For example, if you don't want to get into trouble of hosting it to IIS and editing your hosts file, you could actually change following lines - 

```
var tenant = _context.Tenants.FirstOrDefault(t =>
                t.HostName.Equals(context.Request.Host.Value.ToLower()));
```
to something like - 

```
 var tenantName = context.Request.Query["t"].ToString();

            if (string.IsNullOrWhiteSpace(tenantName))
                tenantName = "tenant1";

var tenant = _context.Tenants.FirstOrDefault(t =>
              t.HostName.StartsWith(tenantName.ToLower()));
```

and provide tenant in query string like `http://<host>:<port>/?t=tenant1`
