### ISSUE TITLE
Mistake in SeedData.cs 

### ISSUE THREAD

**Issue by khatrizeeshan** [janaks09/NetCoreSaaS#6]
NetCoreSaaS/NetCoreSaaS.WebHost/Infrastructures/Helpers/DbHelper/SeedData.cs

  new Tenant
                {
                    TenantId = "14e0af40-3284-4914-bbb2-66330a24482e",
                    Name = "R-Shop",
                    **HostName = "tenant1.localhost:6001",**
                    IsEnabled = true,
                    Server = TenantConstant.LocalServer,
                    Database = "NCS_14e0af40-3284-4914-bbb2-66330a24482e",
                    Subscription = (int)TenantSubscription.Pro,
                    SubscriptionExipreDate = DateTime.UtcNow.AddYears(1), //1 year timeline for pro
                    DbConnectionString = TenantConstant.LocalDbConnectionString,
                    CreatedDate = DateTime.UtcNow,
                    LastUpdated = DateTime.UtcNow
                }

it should be  **HostName = "tenant2.localhost:6001",** i feel.

**Comment by janaks09** [comment]
Thanks. Updated.
