### ISSUE TITLE
Where is the tenant database migrated and updated?

### ISSUE THREAD

**Issue by Jantje2000** [janaks09/NetCoreSaaS#9]
Maybe, I am asking a stupid question, but I cloned this project, and then I made some changes in the tenantdbcontext, because I want to save more data.

However after this, I don't know what to do, to migrate this and update this in the database.
Could anyone help me, to find this?

**Comment by tamnv0310** [comment]
- You can use this command:
 Update-Database -context CatalogDbContext
 Update-Database -context SystemDbContext
- It will appear here:
"ConnectionStrings": {
    "CatalogConnection": "Server=(localdb)\\mssqllocaldb;Database=NetCoreSaaS_Catalogdb;Trusted_Connection=True;MultipleActiveResultSets=true",
    "SystemConnection": "Server=(localdb)\\mssqllocaldb;Database=NetCoreSaaS_Systemdb;Trusted_Connection=True;MultipleActiveResultSets=true"

**Comment by janaks09** [comment]
@Jantje2000 This project does not support update of existing migration. To include another changes you need to re-create whole DB. I used `Database.EnsureCreated();` for test purpose only. For better migration log I would recommend you to use tool/library like DbUp.

**Comment by janaks09** [comment]
@tamnv0310 That will work only for CatalogDbContext and SystemDbContext. To reflect changes made in TenantDbContext, only one way is to re-create whole DB.

I will add DbUp implementation to manage migration of Tenant database.

**Comment by Jantje2000** [comment]
Right, I have fixed it by generating SQL scripts and executing that
